language: c
env:
  - CHANNEL=stable
  - CHANNEL=devel
compiler:
  - gcc
  - clang
matrix:
  allow_failures:
    - env: CHANNEL=devel
  fast_finish: true
install:
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=$HOME/.nimble/bin:$PATH
  - curl -L -o choosenim https://github.com/dom96/choosenim/releases/download/v0.4.0/choosenim-0.4.0_linux_amd64
  - chmod +x choosenim
  - ./choosenim $CHANNEL
script:
    - nim --version
    - nimble build --cc:$CC --debug
cache:
  directories:
    - .choosenim
notifications:
  email: false
