sudo: required
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install -y nim
script:
  - nim c --cc:$CC --verbosity:2 src/rps_nim.nim
notifications:
  email: false
