language: c
env:
  - CHANNEL=stable
  - CHANNEL=devel
compiler:
  - gcc
  - clang
matrix:
  allow_failures:
    - env: CHANNEL=devel
  fast_finish: true
install:
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export CHOOSENIM_NO_ANALYTICS=1
  - yes | choosenim $CHANNEL
before_script:
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh
script:
  - nim --version
  - nimble build --cc:$CC --debug -d:release
cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"
notifications:
  email: false
